services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wingbuddypromo_db
      MYSQL_USER: wingbuddypromo_admin
      MYSQL_PASSWORD: N97a45Drs57a5#6A6E2!rte
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
